# This is the configuration of your book-making machine.
# To store book metadata, rather use the _data folder.

# ------------------------------
# UPDATE THESE SETTINGS ON SETUP
# ------------------------------

# Language
# --------
# The primary language used in this project. You can set the language
# for each book individually below at 'defaults'. 
# To understand what language tags to use, read:
# http://www.w3.org/International/articles/language-tags/ 
# For the registry of tags:
# http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry 
# Useful lookup tool: http://r12a.github.io/apps/subtags/
language: en

# Gem-based theme
# ---------------
# Are you importing a gem-based theme? By default we do not.
# If you are, remove the # before `theme:` and enter your theme's gem name.
# If you're using GitHub Pages, note that it may not support your theme.
# theme: your-theme-gem-name-here

# Custom-edition variable
# -----------------------
# Which edition are we creating? You can leave this as `default`.
# This can be used to create different editions of a book using
# Liquid control-flow tags, e.g. in includes, layouts and file-list
edition: "default"

# Canonical URL
# -------------
# To make absolute links work, e.g. in canonical links in <head>,
# include the url where this site will live when it's live (production).
# E.g. canonical-url: "http://example.com"
# In Open Graph metadata, the base URL will be appended.
canonical-url: "https://survivethecentury.net"

# Base URL
# --------
# If you're using GitHub Pages without a custom domain, make this
# the name of your repo, e.g. /electric-book
# It must start with a slash. Otherwise you can leave it blank. See:
# http://downtothewire.io/2015/08/15/configuring-jekyll-for-user-and-project-github-pages/
baseurl: ""

# GitHub Pages repository
# -----------------------
# If you're publishing a website on GitHub Pages
# and want to ensure you're using a compatible setup,
# add username/repository here and uncomment/enable
# gem 'github-pages', group: :jekyll_plugins
# in this project's Gemfile.
repository: ""

# Navigation
# ----------
# Web navigation source: select either files or nav
# files: navigation will be taken from the web files list in `meta.yml`
# nav: navigation will be taken from the web nav tree in `meta.yml`.
# nav is more powerful, and allows submenu nesting;
# files is quicker, because you don't have to create nav yaml,
# only a files list.
nav-source: nav

# MathJax
# -------
# Enable MathJax to render mathematics. MathJax adds a large script to your pages,
# so this is off (false) by default. Change to true to load MathJax.
# See http://docs.mathjax.org/en/latest/configuration.html for details.
# MathJax scripts are loaded by mathjax-config include, where you can also
# configure MathJax for your project. For MathJax font choices, see
# http://docs.mathjax.org/en/latest/font-support.html
mathjax-enabled: false

# Jekyll collections
# ------------------
# docs:      Documentation is built into the Electric Book template.
#            These docs build along with your books, so they are available
#            as you work. To turn off the docs, change output to false.
# app, epub: The app and epub collections are off by default, and
#            turned on by those formats' _config files.
# items:     Contains repeated items (e.g. text snippets) to be reused
#            across books in this project.
collections:
  docs:
    output: false
  items:
    output: false

# --------------------------------------------
# CHANGE THESE SETTINGS ONLY IF/WHEN NECESSARY
# --------------------------------------------

# Output format
# -------------
# The default output format is 'web'. Don't change this
# unless you really know what you're doing.
# This is overriden by output-specific config files in _configs/
# output: "print-pdf"
# output: "screen-pdf"
output: "web"
# output: "epub"
# output: "app"

# Image set
# ---------
# We use different sets of images for different purposes.
# For instance, small, colour images for epub and screen-pdf, 
# and high-res greyscale for print-pdf.
# This sets the default image set here. This refers to the `images`
# directory in each book's directory, and then to any 
# subdirectories you create per set. Default is images/web.
# This is overriden in output-specific config files in _configs/.
# image-set: "images/print-pdf"
# image-set: "images/screen-pdf"
image-set: "images/web"
# image-set: "images/epub"
# image-set: "images/app"

# Files to exclude from Jekyll build
# ----------------------------------
# Jekyll will ignore these files and folders. 
# This is useful for temporarily speeding up the build to output only certain files.
# Include the file extension too. E.g. book/text/01.md
exclude:
  # Build tools
  - run-linux.sh
  - run-mac.command
  - run-windows.bat
  - Gemfile
  - Gemfile.lock
  - README*
  - LICENSE*
  - CHANGELOG*
  - node_modules
  - eslint.json
  - gulpfile.js
  - package.json
  - package-lock.json
  - CNAME
  - .sass-cache

  # Included as-is in other files, no need to process
  - /assets/js/annotation.js
  - /assets/js/polyfills.js
  - /assets/js/utilities.js
  - /assets/js/settings.js
  - /assets/js/locales.js
  - /assets/js/setup.js
  - /assets/js/mark-parents.js
  - /assets/js/mark.min.js
  - /assets/js/redact.js
  - /assets/js/search-store.js
  - /assets/js/search-terms.js
  - /assets/js/nav.js
  - /assets/js/videos.js
  - /assets/js/mcqs.js
  - /assets/js/select-list.js
  - /assets/js/tables.js
  - /assets/js/footnote-popups.js
  - /assets/js/show-hide.js
  - /assets/js/elasticlunr.min.js
  - /assets/js/elasticlunr-setup.js
  - /assets/js/svg-management.js
  - /assets/js/svg-inject.min.js
  - /assets/js/lazyload.js
  - /assets/js/accordion.js
  - /assets/js/heading-titles.js
  - /assets/js/rotate.js
  - /assets/js/footnotes.js
  - /assets/js/shift-elements.js
  - /assets/js/page-reference.js
  - /assets/js/bookmarks.js

  # Files for formats we're not building here
  - /assets/profiles
  - /*/package.opf
  - /*/toc.ncx
  - /*/images/print-pdf
  - /*/images/screen-pdf
  - /*/images/epub
  - /*/images/app
  - /*/styles/print-pdf*
  - /*/styles/screen-pdf*
  - /*/styles/epub*
  - /*/styles/app*

  # Page types
  # - /book/text/chapter*
  # - /book/text/part-page*
  # - /book/text/newspaper*
  # - /book/text/ending*

  # Files
  - /book/text/0-0-cover.md
  - /book/text/0-1-titlepage.md
  - /book/text/0-2-copyright.md
  - /book/text/0-3-contact.md
  - /book/text/0-4-privacy.md
  - /book/text/0-5-terms-of-service.md
  - /book/text/stc.md
  # - /book/text/chapter_1-5-degree-shocks.md
  # - /book/text/chapter_2-5-degree-shocks.md
  # - /book/text/chapter_3-degree-shocks.md
  # - /book/text/chapter_alarm.md
  # - /book/text/chapter_arctic-extraction.md
  # - /book/text/chapter_armistice.md
  # - /book/text/chapter_bail-out-existing-businesses.md
  # - /book/text/chapter_billionaire-ecotopia-takeover.md
  # - /book/text/chapter_billionaire-geo-engineering.md
  # - /book/text/chapter_billionaires-get-richer.md
  # - /book/text/chapter_birth-rates-plunge.md
  # - /book/text/chapter_carbon-capture.md
  # - /book/text/chapter_central-world-government.md
  # - /book/text/chapter_city-led-capitalist-reform.md
  # - /book/text/chapter_city-led-decarbonization.md
  # - /book/text/chapter_civil-war-version.md
  # - /book/text/chapter_climate-domes.md
  # - /book/text/chapter_climate-hacks-in-conflict.md
  # - /book/text/chapter_corporate-colonialism.md
  # - /book/text/chapter_corporate-forests.md
  # - /book/text/chapter_corporate-housing.md
  # - /book/text/chapter_corporate-orange-zones.md
  # - /book/text/chapter_death-cults.md
  # - /book/text/chapter_democratic-takeover.md
  # - /book/text/chapter_desperation.md
  # - /book/text/chapter_disband-the-militaries.md
  # - /book/text/chapter_earth-terraforming.md
  # - /book/text/chapter_easier-climate-conference.md
  # - /book/text/chapter_eco-mitigation.md
  # - /book/text/chapter_ecocide.md
  # - /book/text/chapter_ecological-technocrats.md
  # - /book/text/chapter_emissions-accounting-argument.md
  # - /book/text/chapter_employment-as-citizenship.md
  # - /book/text/chapter_engineered-crop-blight.md
  # - /book/text/chapter_experimental-orange-zones.md
  # - /book/text/chapter_faffing.md
  # - /book/text/chapter_fail-to-invent-insect-drones.md
  # - /book/text/chapter_fair-vaccine-distribution.md
  # - /book/text/chapter_fast-economic-recovery.md
  # - /book/text/chapter_fossil-fuelled-development.md
  # - /book/text/chapter_fracking-funded-ubi.md
  # - /book/text/chapter_gains-reversed.md
  # - /book/text/chapter_gender-strongmen.md
  # - /book/text/chapter_geo-engineering-fail.md
  # - /book/text/chapter_ghw.md
  # - /book/text/chapter_global-climate-adaptation-fund.md
  # - /book/text/chapter_global-climate-council.md
  # - /book/text/chapter_global-climate-fund.md
  # - /book/text/chapter_global-south-strike.md
  # - /book/text/chapter_global-south-uprising-and-climate-wars.md
  # - /book/text/chapter_global-south-uprising-and-slow-fade.md
  # - /book/text/chapter_goodbye-reproductive-rights.md
  # - /book/text/chapter_grassroots-climate-rebellion.md
  # - /book/text/chapter_grassroots-inequality-rebellion.md
  # - /book/text/chapter_green-is-the-new-gold.md
  # - /book/text/chapter_green-new-deal.md
  # - /book/text/chapter_hackers-attack-space-fleet.md
  # - /book/text/chapter_high-tech-1-5-mitigation.md
  # - /book/text/chapter_human-capital.md
  # - /book/text/chapter_ignored.md
  # - /book/text/chapter_increasing-densification.md
  # - /book/text/chapter_invent-insect-drones.md
  # - /book/text/chapter_invest-in-social-care.md
  # - /book/text/chapter_last-ditch-geo-engineering.md
  # - /book/text/chapter_late-stage-designer-planet.md
  # - /book/text/chapter_late-stage-geo-engineering.md
  # - /book/text/chapter_later-global-south-strike.md
  # - /book/text/chapter_local-communities.md
  # - /book/text/chapter_local-conflicts.md
  # - /book/text/chapter_looser-regulations.md
  # - /book/text/chapter_lucky-procrastinator.md
  # - /book/text/chapter_magic-technology-fix.md
  # - /book/text/chapter_mars-mission.md
  # - /book/text/chapter_martians-return.md
  # - /book/text/chapter_migratory-cities.md
  # - /book/text/chapter_miscalculation.md
  # - /book/text/chapter_monocorp-cities.md
  # - /book/text/chapter_muskbucks.md
  # - /book/text/chapter_no-magic-technology.md
  # - /book/text/chapter_nukes.md
  # - /book/text/chapter_orange-zones.md
  # - /book/text/chapter_patchwork-of-solutions.md
  # - /book/text/chapter_pay-for-transition.md
  # - /book/text/chapter_people-get-richer.md
  # - /book/text/chapter_permanent-refugee-camps.md
  # - /book/text/chapter_post-war-devastation.md
  # - /book/text/chapter_quash-terrorists.md
  # - /book/text/chapter_red-zones.md
  # - /book/text/chapter_reform-capitalism.md
  # - /book/text/chapter_refugee-conflict.md
  # - /book/text/chapter_refugee-crisis-and-billionaire-world.md
  # - /book/text/chapter_refugee-crisis-and-climate-war-world.md
  # - /book/text/chapter_refugee-crisis-and-designer-world.md
  # - /book/text/chapter_refugee-crisis-and-resilient-world.md
  # - /book/text/chapter_refugee-crisis-and-slow-fade-world.md
  # - /book/text/chapter_rewild.md
  # - /book/text/chapter_rogue-climate-hackers.md
  # - /book/text/chapter_seething-underclass.md
  # - /book/text/chapter_sexual-revolution.md
  # - /book/text/chapter_slow-down.md
  # - /book/text/chapter_slow-economic-recovery.md
  # - /book/text/chapter_small-scale-conflict.md
  # - /book/text/chapter_small-scale-wars.md
  # - /book/text/chapter_stalling.md
  # - /book/text/chapter_state-led-decarbonization.md
  # - /book/text/chapter_strongmen.md
  # - /book/text/chapter_sudden-warming.md
  # - /book/text/chapter_surprising-success-geo-engineering.md
  # - /book/text/chapter_termination-shock.md
  # - /book/text/chapter_thats-a-chinese-land-grab.md
  # - /book/text/chapter_the-end-of-nation-states.md
  # - /book/text/chapter_the-wars-begin.md
  # - /book/text/chapter_transitional-fracking.md
  # - /book/text/chapter_ubi.md
  # - /book/text/chapter_undermine-grassroots-rebellion-hooligans.md
  # - /book/text/chapter_undermine-grassroots-rebellion-war.md
  # - /book/text/chapter_unilateral-geo-engineering.md
  # - /book/text/chapter_volcanic-eruption.md
  # - /book/text/chapter_war-over-orange-zones.md
  # - /book/text/chapter_weak-reforms.md
  # - /book/text/chapter_welcome-to-2021.md
  # - /book/text/chapter_well-researched-geo-engineering.md
  # - /book/text/chapter_who-looks-after-the-wild.md
  # - /book/text/chapter_world-trade-is-in-tatters.md
  # - /book/text/chapter_zoonotic-pandemic.md
  # - /book/text/ending_2100-billionaire-ecotopia.md
  # - /book/text/ending_2100-billionaire-saviours.md
  # - /book/text/ending_2100-climate-wars.md
  # - /book/text/ending_2100-designer-planet.md
  # - /book/text/ending_2100-ecotopia.md
  # - /book/text/ending_2100-slow-fade.md
  # - /book/text/ending_dead.md
  # - /book/text/newspaper_welcome-to-2030-billionaire-saviours.md
  # - /book/text/newspaper_welcome-to-2030-climate-wars.md
  # - /book/text/newspaper_welcome-to-2030-designer-planet.md
  # - /book/text/newspaper_welcome-to-2030-ecotopia.md
  # - /book/text/newspaper_welcome-to-2030-slow-fade.md
  # - /book/text/newspaper_welcome-to-2040-billionaire-saviours.md
  # - /book/text/newspaper_welcome-to-2040-climate-wars.md
  # - /book/text/newspaper_welcome-to-2040-designer-planet.md
  # - /book/text/newspaper_welcome-to-2040-ecotopia.md
  # - /book/text/newspaper_welcome-to-2040-slow-fade.md
  # - /book/text/newspaper_welcome-to-2050-billionaire-saviours.md
  # - /book/text/newspaper_welcome-to-2050-climate-wars.md
  # - /book/text/newspaper_welcome-to-2050-designer-planet.md
  # - /book/text/newspaper_welcome-to-2050-ecotopia.md
  # - /book/text/newspaper_welcome-to-2050-slow-fade.md
  # - /book/text/newspaper_welcome-to-2060-billionaire-saviours.md
  # - /book/text/newspaper_welcome-to-2060-climate-wars.md
  # - /book/text/newspaper_welcome-to-2060-designer-planet.md
  # - /book/text/newspaper_welcome-to-2060-ecotopia.md
  # - /book/text/newspaper_welcome-to-2060-slow-fade.md
  # - /book/text/newspaper_welcome-to-2070-billionaire-saviours.md
  # - /book/text/newspaper_welcome-to-2070-climate-wars.md
  # - /book/text/newspaper_welcome-to-2070-designer-planet.md
  # - /book/text/newspaper_welcome-to-2070-ecotopia.md
  # - /book/text/newspaper_welcome-to-2070-slow-fade.md
  # - /book/text/newspaper_welcome-to-2080-billionaire-saviours.md
  # - /book/text/newspaper_welcome-to-2080-climate-wars.md
  # - /book/text/newspaper_welcome-to-2080-designer-planet.md
  # - /book/text/newspaper_welcome-to-2080-ecotopia.md
  # - /book/text/newspaper_welcome-to-2080-slow-fade.md
  # - /book/text/newspaper_welcome-to-2090-billionaire-ecotopia-takeover.md
  # - /book/text/newspaper_welcome-to-2090-billionaire-saviours.md
  # - /book/text/newspaper_welcome-to-2090-climate-wars.md
  # - /book/text/newspaper_welcome-to-2090-designer-planet.md
  # - /book/text/newspaper_welcome-to-2090-ecotopia.md
  # - /book/text/newspaper_welcome-to-2090-slow-fade-conflict.md
  # - /book/text/newspaper_welcome-to-2090-slow-fade-migration.md
  # - /book/text/part-page_2030.md
  # - /book/text/part-page_2040.md
  # - /book/text/part-page_2050.md
  # - /book/text/part-page_2060.md
  # - /book/text/part-page_2070.md
  # - /book/text/part-page_2080.md
  # - /book/text/part-page_2090.md
  # - /book/text/story_blue-queen-of-dc.md
  # - /book/text/story_exile-nation.md
  # - /book/text/story_fashion-week.md
  # - /book/text/story_gipss.md
  # - /book/text/story_green-mall-review.md
  # - /book/text/story_leaked-transcript.md
  # - /book/text/story_lena-lenin.md
  # - /book/text/story_mass-abductions.md
  # - /book/text/story_matrimony.md
  # - /book/text/story_meat-raid.md
  # - /book/text/story_obituary-for-capitalism.md
  # - /book/text/story_reddit.md
  # - /book/text/story_snow-day.md
  # - /book/text/story_statement-from-womb-riot.md
  # - /book/text/story_tate-twilight.md
  # - /book/text/story_trouble-in-paradys.md
  # - /book/text/story_vaccine-queen.md
  # - /book/text/story_your-ticket-to-mars.md

# Files to keep from the last Jekyll build
# ----------------------------------------
# You can prevent Jekyll from overwriting certain files in _site.
# E.g. generate CSS once, then exclude it above but keep it here
# to make your build (i.e. output regeneration) faster.
# The file path is relative to the _site directory.
keep_files:
  # - book
  # - assets

# HTML compression
# ----------------
# Configure HTML compression
# These settings control how your output HTML is compressed.
# See https://github.com/penibelst/jekyll-compress-html
compress_html:
  blanklines: true

# ----------------------------
# DO NOT CHANGE THESE SETTINGS
# ----------------------------

# Electric Book template version
# ------------------------------
# Version of this Electric Book template.
# This is the last release, not necessarily the current build
# at github.com/electricbookworks/electric-book
version: "0.19.0"

# Local-build URL
# ---------------
# Leave this unchanged as http://localhost:4000
# unless you really know what you're doing here.
# This is the URL that Jekyll will run at by default locally.
url: http://localhost:4000

# Markdown processor
# ------------------
# Leave this unchanged as kramdown, unless
# you really know how and why to change your markdown processor.
markdown: kramdown

# kramdown options
# ----------------
# kramdown options (see http://kramdown.gettalong.org/options.html)
# auto_id_stripping removes formatting from headings before generating IDs,
# which keeps your IDs neat and tidy, and your links persistent 
# even if you format headings.
kramdown:
  auto_id_stripping: true

# Permalinks
# ----------
# Leave this unchanged as none. This way, your book's chapters
# will all build named correctly in one folder. This is
# important for rendering and packaging files for PDF and epub.
permalink: none

# Sass
# ----
# Leave this unchanged. It tells Jekyll where to find Sass partials
# (see http://jekyllrb.com/docs/assets/#sassscss)
# and whether to compress stylesheets
sass:
  sass_dir: _sass
  style: compressed

# Default page variables
# ----------------------
# Set default values here for all documents/pages in this publication. 
# (For technical details, see http://jekyllrb.com/docs/configuration/#front-matter-defaults).
# Store only site configurations here, and book metadata (title, author, ISBNs) in _data/meta.yml
defaults: 
  -
    scope: # Sets default page frontmatter for all files in this project (an empty string "" for path means all files).
      path: ""
    values:
      layout: "default"
      style: "chapter"
