# Electric Book settings

# ----------------------------------------------------------
# Electric Book Manager
# ---------------------
electric-book-manager: enable
electric-book-manager-key: ""

# ----------------------------------------------------------
# Print-PDF settings
# ------------
print-pdf:
  # Choose between endnotes or footnotes (endnotes are default)
  # (You can also set this per markdown file with notes: footnotes,
  # or per endnote by adding .move-to-footnote to it.)
  notes: endnotes

# ----------------------------------------------------------
# Web settings
# ------------
web:
  # ----------
  # Pagination
  # ----------
  pagination: false
  # Choose 'direction' for 'Next/Previous' pagination,
  # or 'titles' to show page titles at pagination,
  # or 'arrows' to use only arrows.
  pagination-type: "arrows"
  # --------
  # Masthead
  # --------
  # What kind of header do you want in the masthead? Options:
  # project-name, book-title, page-title, breadcrumbs
  # If not set, book-title is default.
  # Note that breadcrumbs slows your Jekyll build significantly.
  masthead:
    content: book-title
  # -----------------
  # Content accordion
  # -----------------
  # Do you want to collapse content sections in chapters on a
  # particular heading level? Default h2, set in accordion.js.
  # Set this to true to enable, or false to disable.
  accordion: false
  # Enable annotation
  # You can have annotation on for development and/or for live.
  # Set each to either true or false
  annotator:
    development: false
    live: false
  # MathJax is activated in _config.yml. Further settings here.
  # At `source` choose local (`local`) MathJax.js or the CDN (`cdn`).
  mathjax:
    source: cdn
  # --------------
  # SVG management
  # --------------
  # By default on the web, we'll inject SVG as img tags into the page
  # so that you can control fonts and other SVG features with CSS.
  # This works for figure and image includes, and any image with
  # a 'inject-svg' class.
  # If you use injected SVGs, make sure their styles are inline,
  # or SVGs may end up 'sharing' styles for duplicated classes.
  # Advanced: see font-switching options in assets/js/svg-management.js
  # Set 'inject' to false to disable SVG injection.
  svg:
    inject: true
  # -----------------
  # Images management
  # -----------------
  images:
    lazyload: true
  # -----------------
  # Bookmarks
  # -----------------
  bookmarks: false
  # --------------
  # Navigation
  # --------------
  # On your landing page, should books in the nav expand
  # to include chapters? Expanding many chapters can
  # make your pages much bigger and slower. true/false
  nav:
    home:
      expand-books: false

# ----------------------------------------------------------
# General output options
# ----------------------
# If included items are missing, do we show an error in output,
# or does the site build break completely? Default is to break.
on-missing-item: error
# Redact elements with the 'redact' class: true or false
redact: false
